/* tslint:disable */
// This file is generated
// Do not edit this file
import * as sendData from "./sendData/index";
export * as sendData from "./sendData/index";

export type Actions = {
  sendData: sendData.ActionSendData;
}
